### PR TITLE
Issue/242 fix iphone x layout issues

### LINKED ISSUE #242: Layout issues on iPhone X
### Expected behavior

On iPhoneX the layout shouldn't go bellow the notch, avoid the round corners and get a good margin from the bottom home area.

### Actual behavior

On landscape mode the layout is going through all the areas mentioned above

### Steps to reproduce the behavior

Start the demo app, open the input media picker or the full screen version.
Rotate to landscape
Scroll around.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #242 

To test:
 - Start the demo app on iPhoneX
 - Check if the layout is working around the notch and the home area
 - Start the demo app on another device
 - Check that all still works correctly

### CODE REVIEW

File: Pod/Classes/WPInputMediaPickerViewController.m [hunk 1]
```diff
@@ -51,10 +51,30 @@ - (void)setupMediaPickerViewController {
...
     
     self.mediaPicker.view.frame = self.view.bounds;
-    self.mediaPicker.view.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;    
+    self.mediaPicker.view.translatesAutoresizingMaskIntoConstraints = NO;
     [self.view addSubview:self.mediaPicker.view];
+    if (@available(iOS 11.0, *)) {
+        UILayoutGuide *layoutGuide = self.view.safeAreaLayoutGuide;
+        [NSLayoutConstraint activateConstraints:
+         @[
+           [self.mediaPicker.view.leadingAnchor constraintEqualToAnchor:layoutGuide.leadingAnchor constant:0],
```
Comment (frosty) [inline Pod/Classes/WPInputMediaPickerViewController.m]: You can omit the `constant` parameter entirely for all these calls.

File: Pod/Classes/WPMediaPickerViewController.m [hunk 2]
```diff
@@ -118,7 +118,9 @@ - (void)viewDidLoad
     } else {
         [self.view addGestureRecognizer:self.longPressGestureRecognizer];
     }
-
+    if (@available(iOS 11.0, *)) {
```
Comment (frosty) [inline Pod/Classes/WPMediaPickerViewController.m]: Nitpick, but could you add a blank line above and below this `if`, just to help readability?

File: Pod/Classes/WPInputMediaPickerViewController.m [hunk 3]
```diff
@@ -51,10 +51,30 @@ - (void)setupMediaPickerViewController {
...
+           [self.mediaPicker.view.trailingAnchor constraintEqualToAnchor:layoutGuide.trailingAnchor constant:0],
+           [self.mediaPicker.view.topAnchor constraintEqualToAnchor:layoutGuide.topAnchor constant:0],
```
Comment (frosty) [inline Pod/Classes/WPInputMediaPickerViewController.m]: I think we need to continue to use the view's top and bottom anchors, otherwise there's an issue where the collection view never scrolls behind the home indicator (content should flow behind it):

simulator screen shot - iphone x - 2017-09-25 at 17 43 07

We could clean this section up by doing something like this:

```
NSLayoutAnchor *leadingAnchor = self.view.leadingAnchor;
NSLayoutAnchor *trailingAnchor = self.view.trailingAnchor;

if (@available(iOS 11.0, *)) {
    leadingAnchor = self.view.safeAreaLayoutGuide.leadingAnchor;
    trailingAnchor = self.view.safeAreaLayoutGuide.trailingAnchor;
}

[NSLayoutConstraint activateConstraints: @[
   [self.mediaPicker.view.leadingAnchor constraintEqualToAnchor:leadingAnchor constant:0],
   [self.mediaPicker.view.trailingAnchor constraintEqualToAnchor:trailingAnchor constant:0],
   [self.mediaPicker.view.topAnchor constraintEqualToAnchor:self.view.topAnchor constant:0],
   [self.mediaPicker.view.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor constant:0]
   ]];
```

Comment (SergioEstevao) [reply Pod/Classes/WPInputMediaPickerViewController.m]: The issue with that is when you have a horizontal scroll....

**Comment by SergioEstevao** [comment]
@frosty fixed the issues you referred above and also the bounce problem when scrolling.
