### PR TITLE
Issue/135: Don't silently pass through face up/down device orientations

### LINKED ISSUE #135: Camera preview orientation incorrect when tilted forward
When holding my phone in portrait orientation, if I tilt it forward past about 45 degrees the camera preview header flips into landscape orientation. I did this when getting ready to take a picture pointing straight down at my desk. It's worth noting that both my phone and the camera app's orientations were still portrait at this point.

Tested: Latest WPiOS 6.9 beta build, iPhone 7, iOS 10.2.1

### PR DESCRIPTION
**Pull request by frosty**
Fixes #135.

The camera preview image was getting flipped when holding the device in portrait and then tilting it forward (as though you were going to point it downwards). This seemed to be because we were casting `UIDeviceOrientation` directly to `AVCaptureVideoOrientation`, but `AVCaptureVideoOrientation` has two extra Face Up / Face Down cases that the AV enum doesn't have. To fix the issue, we convert either of those cases to `AVCaptureVideoOrientationPortrait`.

To test:

* Run on a device
* Open the picker and look at the camera preview cell
* Hold the device in portrait
* Slowly tilt the device forward until you're pointing the camera down at the floor. Check the preview image is still orientated correctly
* Check that landscape orientations still work correctly too.

Needs review: @SergioEstevao

### CODE REVIEW

File: Pod/Classes/WPMediaCapturePreviewCollectionView.m [hunk 1]
```diff
@@ -110,10 +110,19 @@ - (void)startCapture
...
     }
 }
 
+- (AVCaptureVideoOrientation)videoOrientationForDeviceOrientation:(UIDeviceOrientation)orientation
+{
+    if (orientation == UIDeviceOrientationFaceUp || orientation == UIDeviceOrientationFaceDown) {
+        return AVCaptureVideoOrientationPortrait;
+    }
+
+    return (AVCaptureVideoOrientation)orientation;
```
Comment (koke) [inline Pod/Classes/WPMediaCapturePreviewCollectionView.m]: `AVCaptureVideoOrientation` can't be directly mapped to `UIDeviceOrientation`, as their values are different.

**Comment by frosty** [comment]
Thanks @koke, I hadn't thought about landscape using face down orientation too. I've switched things over to use the interface orientation, as you suggested, and I've explicitly mapped to the correct values.

Better?

**Comment by frosty** [comment]
Thanks @SergioEstevao and @koke!
